"""Curated US expense vocabulary: merchants, items, and realistic amounts.

This is the source of truth for both the categorizer's exemplar corpus
(``tools/build_training_data.py``) and the demo account's transactions
(``tools/build_demo_data.py``). One spec feeds both, so the demo shows the same
merchants the model was trained to recognise.

Why this replaced the previous corpus
-------------------------------------
The old corpus was built from ``data/categories.csv`` (bare keywords pushed
through four fixed templates) plus ``data/sample-data.csv`` (one person's
anonymised Indian expense ledger). Three things were wrong with it:

* **It didn't look like the queries.** ``pipeline.process_transcript`` asks the
  categorizer about ``"{description} {merchant}"`` -- "coffee starbucks" -- but
  only 1.3% of the old exemplars contained a brand name at all. The one signal
  the pipeline deliberately adds was the one the corpus couldn't match on.
* **Two categories were unreachable.** ``Apparel`` and ``Entertainment`` are in
  the app's category list, but the old builder folded them into Household and
  Social Life, so no exemplar could ever vote for them.
* **The tail was starved and narrow.** Subscription had 60 exemplars and every
  one was a video streaming service, so "gym membership" or "iCloud storage"
  matched nothing.

Structure
---------
A category is a list of :class:`Group`\\ s rather than one flat merchant list.
A group is a set of merchants that sell the same kind of thing, paired with the
items they actually sell. Pairing across the whole category instead produces
exemplars like "museum admission steam" or "opera tickets sea world" -- same
label, so accuracy barely notices, but it thins out the regions of the vector
space that should be dense and makes the corpus unreadable to a human
reviewing it.

Taxonomy judgment calls, written down rather than left implicit. These decide
the otherwise-ambiguous rows, and the old corpus lost accuracy precisely where
they were vague:

* **Entertainment vs Social Life.** Entertainment is paid media and venues you
  buy a ticket to (movies, concerts, games, museums). Social Life is time spent
  with people (bars, gifts, parties). A cinema ticket is Entertainment; a bar
  tab is Social Life.
* **Household vs Subscription.** Household covers the home, including utilities
  and home internet. Subscription covers recurring personal services
  (streaming, software, gym, phone plan).
* **Health vs Household.** Pharmacies sell both. Prescriptions, copays, and
  treatment are Health; shampoo and paper towels from the same store are
  Household.
* **Transportation vs Tourism.** Getting around day to day is Transportation
  (gas, transit, rideshare, parking). Travelling away from home is Tourism
  (flights, hotels, rental cars).

Rent and tuition are deliberately absent from the amount ranges. Both are real
expenses, but the demo seeder samples its pool uniformly, so an $1,800 rent row
would surface a random number of times per month and wreck the forecast. They
belong to a recurring-transaction feature that doesn't exist yet.
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Group:
    """Merchants that sell the same kind of thing, and the things they sell.

    ``amount_range`` overrides the category default where a sub-domain spends
    differently -- a coffee run and a grocery haul are both Food, but seeding
    the demo with $80 lattes would look absurd.
    """

    merchants: list[str]
    items: list[str]
    amount_range: tuple[float, float] | None = None


@dataclass(frozen=True)
class CategorySpec:
    """Vocabulary and typical spend for one category."""

    groups: list[Group]
    amount_range: tuple[float, float]
    big_ticket: tuple[float, float] | None = None
    big_ticket_rate: float = 0.12
    # Phrases that stand on their own with no merchant ("copay", "electric
    # bill"). Real descriptions are often exactly this.
    standalone: list[str] = field(default_factory=list)
    # Brands you pay a bill to rather than buy things from. Kept apart from
    # group merchants so the builder never emits "toilet paper Comcast".
    billers: list[str] = field(default_factory=list)


SPEC: dict[str, CategorySpec] = {
    "Food": CategorySpec(
        groups=[
            Group(
                merchants=[
                    "Starbucks",
                    "Dunkin",
                    "Peet's",
                    "Caribou Coffee",
                    "Tim Hortons",
                    "Krispy Kreme",
                    "Jamba Juice",
                    "Blue Bottle",
                    "Dutch Bros",
                ],
                items=[
                    "coffee",
                    "latte",
                    "iced coffee",
                    "cold brew",
                    "cappuccino",
                    "espresso",
                    "americano",
                    "chai latte",
                    "breakfast sandwich",
                    "bagel",
                    "donuts",
                    "muffin",
                    "croissant",
                    "smoothie",
                    "pastry",
                ],
                amount_range=(3.75, 14.0),
            ),
            Group(
                merchants=[
                    "Chipotle",
                    "McDonald's",
                    "Subway",
                    "Taco Bell",
                    "Chick-fil-A",
                    "Wendy's",
                    "Burger King",
                    "Popeyes",
                    "KFC",
                    "Five Guys",
                    "Shake Shack",
                    "In-N-Out",
                    "Panda Express",
                    "Jimmy John's",
                    "Jersey Mike's",
                    "Panera",
                    "Sweetgreen",
                    "Raising Cane's",
                    "Whataburger",
                    "Culver's",
                    "Arby's",
                    "Sonic",
                ],
                items=[
                    "lunch",
                    "dinner",
                    "burrito bowl",
                    "burrito",
                    "tacos",
                    "burger",
                    "fries",
                    "sandwich",
                    "sub",
                    "salad",
                    "wings",
                    "fried chicken",
                    "nuggets",
                    "combo meal",
                    "takeout",
                    "quesadilla",
                    "bowl",
                ],
                amount_range=(7.5, 26.0),
            ),
            Group(
                merchants=["Domino's", "Pizza Hut", "Papa John's", "Little Caesars", "Blaze Pizza"],
                items=["pizza", "large pizza", "pizza delivery", "wings", "breadsticks", "slice"],
                amount_range=(11.0, 38.0),
            ),
            Group(
                merchants=[
                    "Olive Garden",
                    "Applebee's",
                    "Chili's",
                    "IHOP",
                    "Denny's",
                    "Waffle House",
                    "Cheesecake Factory",
                    "Buffalo Wild Wings",
                    "Red Robin",
                    "Texas Roadhouse",
                    "Outback",
                    "Red Lobster",
                    "Cracker Barrel",
                    "First Watch",
                ],
                items=[
                    "lunch",
                    "dinner",
                    "brunch",
                    "breakfast",
                    "steak dinner",
                    "bbq",
                    "burger",
                    "wings",
                    "appetizers",
                    "pasta",
                    "family dinner",
                ],
                amount_range=(18.0, 72.0),
            ),
            Group(
                merchants=[
                    "Whole Foods",
                    "Trader Joe's",
                    "Kroger",
                    "Safeway",
                    "Publix",
                    "Aldi",
                    "Wegmans",
                    "H-E-B",
                    "Sprouts",
                    "Food Lion",
                    "Giant",
                    "Meijer",
                    "Stop & Shop",
                    "Winn-Dixie",
                    "Albertsons",
                ],
                items=[
                    "groceries",
                    "grocery run",
                    "weekly groceries",
                    "milk",
                    "eggs",
                    "bread",
                    "produce",
                    "vegetables",
                    "fruit",
                    "chicken",
                    "ground beef",
                    "cereal",
                    "snacks",
                    "chips",
                    "ice cream",
                    "frozen pizza",
                    "pasta",
                    "rice",
                    "coffee beans",
                    "yogurt",
                    "cheese",
                    "orange juice",
                    "peanut butter",
                    "olive oil",
                ],
                amount_range=(12.0, 130.0),
            ),
            Group(
                merchants=[
                    "DoorDash",
                    "Uber Eats",
                    "Grubhub",
                    "Instacart",
                    "Postmates",
                    "Seamless",
                ],
                items=[
                    "delivery",
                    "food delivery",
                    "takeout",
                    "dinner delivery",
                    "lunch delivery",
                    "grocery delivery",
                    "late night order",
                ],
                amount_range=(14.0, 52.0),
            ),
            Group(
                merchants=["Panda Express", "Pei Wei", "Noodles & Company", "Chopt", "Cava"],
                items=[
                    "sushi",
                    "ramen",
                    "pho",
                    "curry",
                    "pad thai",
                    "noodles",
                    "dumplings",
                    "poke bowl",
                ],
                amount_range=(10.0, 34.0),
            ),
        ],
        standalone=[
            "lunch",
            "dinner",
            "groceries",
            "takeout",
            "coffee",
            "snacks",
            "office lunch",
            "team lunch",
            "food truck",
            "farmers market",
            "vending machine",
            "gas station snacks",
        ],
        amount_range=(4.0, 40.0),
        big_ticket=(75.0, 165.0),
    ),
    "Transportation": CategorySpec(
        groups=[
            Group(
                merchants=["Uber", "Lyft", "Curb", "Via"],
                items=[
                    "ride",
                    "ride home",
                    "ride to work",
                    "airport ride",
                    "rideshare",
                    "late night ride",
                    "ride downtown",
                    "surge ride",
                    "cab",
                    "taxi",
                ],
                amount_range=(8.0, 45.0),
            ),
            Group(
                merchants=[
                    "Shell",
                    "Chevron",
                    "Exxon",
                    "BP",
                    "Mobil",
                    "Sunoco",
                    "Speedway",
                    "Wawa",
                    "QuikTrip",
                    "Circle K",
                    "Sheetz",
                    "Marathon",
                    "Costco Gas",
                    "Sam's Club Gas",
                    "76",
                    "Arco",
                    "Citgo",
                    "Valero",
                    "RaceTrac",
                ],
                items=[
                    "gas",
                    "gas fill up",
                    "fill up",
                    "fuel",
                    "tank of gas",
                    "premium gas",
                    "half tank",
                    "diesel",
                ],
                amount_range=(28.0, 78.0),
            ),
            Group(
                merchants=[
                    "MTA",
                    "BART",
                    "CTA",
                    "WMATA",
                    "SEPTA",
                    "Muni",
                    "Metro",
                    "Amtrak",
                    "Caltrain",
                    "NJ Transit",
                    "MARTA",
                ],
                items=[
                    "subway fare",
                    "metro card",
                    "bus fare",
                    "transit pass",
                    "train ticket",
                    "monthly transit pass",
                    "commuter rail",
                    "light rail fare",
                    "fare reload",
                ],
                amount_range=(2.75, 42.0),
            ),
            Group(
                merchants=["E-ZPass", "SpotHero", "ParkMobile", "LAZ Parking", "SunPass"],
                items=[
                    "parking",
                    "parking garage",
                    "parking meter",
                    "monthly parking",
                    "toll",
                    "tolls",
                    "bridge toll",
                    "express lane",
                    "street parking",
                    "event parking",
                ],
                amount_range=(3.0, 32.0),
            ),
            Group(
                merchants=[
                    "Jiffy Lube",
                    "Valvoline",
                    "Discount Tire",
                    "AutoZone",
                    "O'Reilly",
                    "Firestone",
                    "Midas",
                    "Les Schwab",
                    "Pep Boys",
                    "NAPA Auto Parts",
                    "Advance Auto Parts",
                ],
                items=[
                    "oil change",
                    "car wash",
                    "tire rotation",
                    "new tires",
                    "brake pads",
                    "wiper blades",
                    "car battery",
                    "engine air filter",
                    "smog check",
                    "emissions test",
                    "windshield wipers",
                    "coolant",
                    "alignment",
                    "inspection",
                ],
                amount_range=(22.0, 190.0),
            ),
            Group(
                merchants=["Zipcar", "Lime", "Bird", "Citi Bike", "Divvy"],
                items=["scooter rental", "bike share", "bike rental", "day pass"],
                amount_range=(4.0, 26.0),
            ),
        ],
        standalone=[
            "gas",
            "parking",
            "toll",
            "car payment",
            "registration renewal",
            "dmv fee",
            "license renewal",
            "car insurance",
            "roadside assistance",
            "jump start",
            "tow truck",
            "uber to the airport",
        ],
        amount_range=(3.0, 58.0),
        big_ticket=(95.0, 430.0),
    ),
    "Apparel": CategorySpec(
        groups=[
            Group(
                merchants=[
                    "Nike",
                    "Adidas",
                    "Puma",
                    "Under Armour",
                    "New Balance",
                    "Foot Locker",
                    "DSW",
                    "Famous Footwear",
                    "Vans",
                    "Converse",
                    "Sketchers",
                    "Allbirds",
                    "Brooks",
                ],
                items=[
                    "sneakers",
                    "running shoes",
                    "trainers",
                    "basketball shoes",
                    "boots",
                    "sandals",
                    "slides",
                    "cleats",
                    "shoe insoles",
                    "athletic socks",
                ],
                amount_range=(28.0, 145.0),
            ),
            Group(
                merchants=[
                    "H&M",
                    "Zara",
                    "Uniqlo",
                    "Gap",
                    "Old Navy",
                    "Banana Republic",
                    "J.Crew",
                    "Levi's",
                    "American Eagle",
                    "Aerie",
                    "Madewell",
                    "Everlane",
                    "Urban Outfitters",
                    "ASOS",
                    "Shein",
                    "Abercrombie",
                    "Express",
                    "Forever 21",
                ],
                items=[
                    "jeans",
                    "t-shirt",
                    "shirt",
                    "dress shirt",
                    "polo",
                    "blouse",
                    "dress",
                    "jacket",
                    "hoodie",
                    "sweatshirt",
                    "sweater",
                    "cardigan",
                    "shorts",
                    "chinos",
                    "slacks",
                    "skirt",
                    "socks",
                    "underwear",
                    "pajamas",
                    "swimsuit",
                    "swim trunks",
                    "belt",
                    "new outfit",
                    "work clothes",
                    "school clothes",
                ],
                amount_range=(16.0, 88.0),
            ),
            Group(
                merchants=[
                    "Lululemon",
                    "Athleta",
                    "Patagonia",
                    "The North Face",
                    "Columbia",
                    "REI",
                    "Fabletics",
                    "Gymshark",
                ],
                items=[
                    "leggings",
                    "yoga pants",
                    "workout clothes",
                    "gym shorts",
                    "winter coat",
                    "rain jacket",
                    "fleece",
                    "base layer",
                    "hiking pants",
                    "puffer jacket",
                    "sports bra",
                ],
                amount_range=(38.0, 185.0),
            ),
            Group(
                merchants=[
                    "Nordstrom",
                    "Nordstrom Rack",
                    "Macy's",
                    "TJ Maxx",
                    "Marshalls",
                    "Ross",
                    "Burlington",
                    "Kohl's",
                    "Dillard's",
                    "Poshmark",
                    "ThredUp",
                ],
                items=[
                    "dress shoes",
                    "heels",
                    "suit",
                    "blazer",
                    "dress",
                    "coat",
                    "interview outfit",
                    "dress for the wedding",
                    "scarf",
                    "gloves",
                    "hat",
                    "beanie",
                    "sunglasses",
                    "handbag",
                    "wallet",
                ],
                amount_range=(20.0, 160.0),
            ),
        ],
        standalone=[
            "new shoes",
            "new jeans",
            "clothes",
            "clothing",
            "shoe repair",
            "tailoring",
            "dry cleaning",
            "alterations",
            "winter clothes",
        ],
        amount_range=(16.0, 98.0),
        big_ticket=(140.0, 350.0),
    ),
    "Household": CategorySpec(
        groups=[
            Group(
                merchants=[
                    "Target",
                    "Walmart",
                    "Amazon",
                    "Costco",
                    "Sam's Club",
                    "Dollar General",
                    "Dollar Tree",
                    "Family Dollar",
                    "Big Lots",
                ],
                items=[
                    "paper towels",
                    "toilet paper",
                    "laundry detergent",
                    "dish soap",
                    "dishwasher pods",
                    "trash bags",
                    "cleaning supplies",
                    "all purpose cleaner",
                    "sponges",
                    "bleach",
                    "fabric softener",
                    "hand soap",
                    "air freshener",
                    "shampoo",
                    "conditioner",
                    "body wash",
                    "toothpaste",
                    "toothbrush",
                    "razors",
                    "shaving cream",
                    "deodorant",
                    "lotion",
                    "sunscreen",
                    "paper plates",
                    "ziploc bags",
                    "aluminum foil",
                    "batteries",
                ],
                amount_range=(7.0, 68.0),
            ),
            Group(
                merchants=[
                    "Home Depot",
                    "Lowe's",
                    "Ace Hardware",
                    "Menards",
                    "True Value",
                    "Harbor Freight",
                ],
                items=[
                    "light bulbs",
                    "extension cord",
                    "air filter",
                    "furnace filter",
                    "smoke detector",
                    "duct tape",
                    "screwdriver set",
                    "drill bits",
                    "nails",
                    "screws",
                    "paint",
                    "caulk",
                    "hose",
                    "potting soil",
                    "lawn bags",
                    "weed killer",
                    "door handle",
                    "shelf brackets",
                ],
                amount_range=(9.0, 95.0),
            ),
            Group(
                merchants=[
                    "IKEA",
                    "Bed Bath & Beyond",
                    "Wayfair",
                    "The Container Store",
                    "HomeGoods",
                    "Crate & Barrel",
                    "West Elm",
                    "Pottery Barn",
                    "Overstock",
                ],
                items=[
                    "towels",
                    "bedding",
                    "sheets",
                    "pillows",
                    "comforter",
                    "shower curtain",
                    "lamp",
                    "curtains",
                    "rug",
                    "storage bins",
                    "hangers",
                    "picture frames",
                    "cookware",
                    "pots and pans",
                    "cutting board",
                    "food containers",
                    "desk chair",
                    "bookshelf",
                    "nightstand",
                    "laundry basket",
                    "trash can",
                ],
                amount_range=(14.0, 165.0),
            ),
        ],
        billers=[
            "Comcast",
            "Xfinity",
            "Spectrum",
            "Cox",
            "Verizon Fios",
            "AT&T Internet",
            "Con Edison",
            "PG&E",
            "Duke Energy",
            "National Grid",
            "Ameren",
            "Georgia Power",
            "Xcel Energy",
            "Dominion Energy",
            "City Utilities",
        ],
        standalone=[
            "electric bill",
            "power bill",
            "water bill",
            "gas bill",
            "utility bill",
            "internet bill",
            "wifi bill",
            "trash pickup",
            "sewer bill",
            "renters insurance",
            "home supplies",
            "household stuff",
            "cleaning service",
            "pest control",
            "hoa dues",
            "lawn service",
        ],
        amount_range=(8.0, 78.0),
        big_ticket=(120.0, 390.0),
    ),
    "Health": CategorySpec(
        groups=[
            Group(
                merchants=[
                    "CVS",
                    "CVS Pharmacy",
                    "Walgreens",
                    "Rite Aid",
                    "GoodRx",
                    "Walmart Pharmacy",
                ],
                items=[
                    "prescription",
                    "prescription refill",
                    "refill",
                    "antibiotics",
                    "allergy medicine",
                    "cold medicine",
                    "cough syrup",
                    "ibuprofen",
                    "advil",
                    "tylenol",
                    "vitamins",
                    "multivitamin",
                    "supplements",
                    "band aids",
                    "first aid kit",
                    "thermometer",
                    "heating pad",
                    "cough drops",
                    "nasal spray",
                    "inhaler refill",
                ],
                amount_range=(6.0, 65.0),
            ),
            Group(
                merchants=[
                    "LensCrafters",
                    "Warby Parker",
                    "Pearle Vision",
                    "Visionworks",
                    "America's Best",
                    "1-800 Contacts",
                ],
                items=[
                    "contact lenses",
                    "contact solution",
                    "glasses",
                    "new glasses",
                    "reading glasses",
                    "eye exam",
                    "prescription sunglasses",
                ],
                amount_range=(25.0, 240.0),
            ),
            Group(
                merchants=[
                    "One Medical",
                    "MinuteClinic",
                    "CityMD",
                    "Zocdoc",
                    "Teladoc",
                    "Kaiser Permanente",
                    "LabCorp",
                    "Quest Diagnostics",
                    "Urgent Care",
                ],
                items=[
                    "visit",
                    "copay",
                    "consultation",
                    "follow up visit",
                    "lab work",
                    "blood work",
                    "test results",
                    "screening",
                ],
                amount_range=(20.0, 190.0),
            ),
            Group(
                merchants=["Aspen Dental", "Delta Dental", "SmileDirectClub", "Invisalign"],
                items=["cleaning", "checkup", "filling", "x-rays", "aligners", "retainer"],
                amount_range=(40.0, 320.0),
            ),
        ],
        standalone=[
            "doctor visit",
            "doctor copay",
            "copay",
            "specialist copay",
            "dentist",
            "dental cleaning",
            "teeth cleaning",
            "cavity filling",
            "root canal",
            "orthodontist",
            "braces payment",
            "urgent care visit",
            "er visit",
            "annual physical",
            "blood work",
            "x-ray",
            "mri",
            "flu shot",
            "vaccine",
            "covid test",
            "therapy session",
            "therapy copay",
            "counseling",
            "chiropractor",
            "physical therapy",
            "pt session",
            "dermatologist",
            "eye doctor",
            "health insurance premium",
            "vision exam",
            "hearing test",
            "prescription copay",
            "urgent care copay",
        ],
        amount_range=(10.0, 90.0),
        big_ticket=(160.0, 640.0),
    ),
    "Education": CategorySpec(
        groups=[
            Group(
                merchants=[
                    "Barnes & Noble",
                    "Campus Bookstore",
                    "Chegg",
                    "AbeBooks",
                    "ThriftBooks",
                ],
                items=[
                    "textbook",
                    "textbooks",
                    "used textbook",
                    "textbook rental",
                    "study guide",
                    "workbook",
                    "course reader",
                    "lab manual",
                ],
                amount_range=(18.0, 180.0),
            ),
            Group(
                merchants=[
                    "Coursera",
                    "Udemy",
                    "edX",
                    "MasterClass",
                    "Skillshare",
                    "Codecademy",
                    "Pluralsight",
                    "LinkedIn Learning",
                    "Brilliant",
                    "DataCamp",
                    "Duolingo",
                ],
                items=[
                    "online course",
                    "course",
                    "certification course",
                    "course enrollment",
                    "specialization",
                    "annual plan",
                ],
                amount_range=(12.0, 120.0),
            ),
            Group(
                merchants=["Staples", "Office Depot", "OfficeMax"],
                items=[
                    "notebook",
                    "notebooks",
                    "pens",
                    "pencils",
                    "highlighters",
                    "binder",
                    "folders",
                    "index cards",
                    "sticky notes",
                    "printer paper",
                    "printer ink",
                    "calculator",
                    "graphing calculator",
                    "flash cards",
                    "planner",
                ],
                amount_range=(6.0, 72.0),
            ),
            Group(
                merchants=["Kaplan", "Princeton Review", "ETS", "College Board", "Pearson VUE"],
                items=[
                    "exam fee",
                    "practice tests",
                    "prep course",
                    "test registration",
                    "score report",
                    "retake fee",
                ],
                amount_range=(35.0, 320.0),
            ),
        ],
        standalone=[
            "tuition payment",
            "student loan payment",
            "lab fee",
            "course fee",
            "registration fee",
            "gre registration",
            "sat fee",
            "certification exam",
            "library fine",
            "printing credits",
            "campus parking permit",
            "tutoring",
            "tutoring session",
            "class materials",
            "semester fees",
            "school supplies",
            "conference registration",
            "workshop fee",
        ],
        amount_range=(9.0, 95.0),
        big_ticket=(160.0, 540.0),
    ),
    "Entertainment": CategorySpec(
        groups=[
            Group(
                merchants=[
                    "AMC",
                    "Regal",
                    "Cinemark",
                    "Alamo Drafthouse",
                    "Fandango",
                    "Marcus Theatres",
                ],
                items=[
                    "movie tickets",
                    "movie ticket",
                    "matinee",
                    "imax tickets",
                    "3d tickets",
                    "popcorn and drinks",
                    "concession stand",
                    "two movie tickets",
                    "opening night tickets",
                ],
                amount_range=(9.0, 44.0),
            ),
            Group(
                merchants=[
                    "Ticketmaster",
                    "StubHub",
                    "SeatGeek",
                    "Live Nation",
                    "Vivid Seats",
                    "AXS",
                ],
                items=[
                    "concert tickets",
                    "show tickets",
                    "festival tickets",
                    "comedy show",
                    "broadway tickets",
                    "theater tickets",
                    "opera tickets",
                    "ballet tickets",
                    "game tickets",
                    "baseball tickets",
                    "basketball tickets",
                    "football tickets",
                    "hockey tickets",
                    "playoff tickets",
                    "tour tickets",
                ],
                amount_range=(35.0, 240.0),
            ),
            Group(
                merchants=[
                    "Dave & Buster's",
                    "Topgolf",
                    "Main Event",
                    "Bowlero",
                    "Chuck E. Cheese",
                    "Round1",
                ],
                items=[
                    "bowling",
                    "mini golf",
                    "arcade games",
                    "laser tag",
                    "go karts",
                    "escape room",
                    "game credits",
                    "batting cages",
                    "axe throwing",
                ],
                amount_range=(14.0, 78.0),
            ),
            Group(
                merchants=[
                    "Six Flags",
                    "Cedar Point",
                    "Universal Studios",
                    "Sea World",
                    "Busch Gardens",
                    "Disneyland",
                ],
                items=[
                    "theme park tickets",
                    "park admission",
                    "season pass",
                    "day pass",
                    "fast pass",
                    "park parking",
                ],
                amount_range=(45.0, 190.0),
            ),
            Group(
                merchants=[
                    "Steam",
                    "PlayStation Store",
                    "Xbox",
                    "Nintendo eShop",
                    "GameStop",
                    "Epic Games",
                    "Humble Bundle",
                    "Battle.net",
                    "itch.io",
                ],
                items=[
                    "video game",
                    "new game",
                    "game preorder",
                    "dlc",
                    "expansion",
                    "in game currency",
                    "controller",
                    "game pass",
                    "bundle",
                ],
                amount_range=(9.0, 72.0),
            ),
            Group(
                merchants=[
                    "Smithsonian",
                    "MoMA",
                    "The Met",
                    "Field Museum",
                    "Exploratorium",
                    "Adler Planetarium",
                ],
                items=[
                    "museum admission",
                    "zoo tickets",
                    "aquarium tickets",
                    "planetarium",
                    "exhibit tickets",
                    "gallery admission",
                ],
                amount_range=(12.0, 48.0),
            ),
            Group(
                merchants=["iTunes", "Google Play", "Vudu", "Redbox"],
                items=["movie rental", "movie purchase", "digital rental", "season pass"],
                amount_range=(4.0, 25.0),
            ),
        ],
        standalone=[
            "movie night",
            "concert",
            "night out",
            "sports game",
            "trivia night",
            "karaoke",
            "book",
            "comic book",
            "magazine",
            "vinyl record",
        ],
        amount_range=(10.0, 72.0),
        big_ticket=(120.0, 350.0),
    ),
    "Social Life": CategorySpec(
        groups=[
            Group(
                merchants=[
                    "Total Wine",
                    "BevMo",
                    "ABC Fine Wine",
                    "Binny's",
                    "Spec's",
                    "Liquor Barn",
                ],
                items=[
                    "wine",
                    "bottle of wine",
                    "six pack",
                    "case of beer",
                    "liquor",
                    "whiskey",
                    "tequila",
                    "vodka",
                    "champagne",
                    "hard seltzer",
                ],
                amount_range=(14.0, 85.0),
            ),
            Group(
                merchants=[
                    "The Local Pub",
                    "Brewery",
                    "Taproom",
                    "Speakeasy",
                    "Sports Bar",
                    "Wine Bar",
                    "Cocktail Bar",
                    "Beer Garden",
                ],
                items=[
                    "drinks",
                    "drinks with friends",
                    "bar tab",
                    "beers",
                    "a round of drinks",
                    "cocktails",
                    "happy hour",
                    "nightcap",
                    "cover charge",
                    "club cover",
                    "bottle service",
                    "pitcher",
                ],
                amount_range=(12.0, 95.0),
            ),
            Group(
                merchants=[
                    "1-800-Flowers",
                    "Edible Arrangements",
                    "Etsy",
                    "Hallmark",
                    "Bath & Body Works",
                    "Yankee Candle",
                    "Sephora",
                    "Papyrus",
                ],
                items=[
                    "birthday gift",
                    "wedding gift",
                    "baby shower gift",
                    "holiday gift",
                    "christmas gifts",
                    "graduation gift",
                    "housewarming gift",
                    "gift card",
                    "flowers",
                    "bouquet",
                    "greeting card",
                    "thank you gift",
                    "anniversary gift",
                ],
                amount_range=(15.0, 110.0),
            ),
            Group(
                merchants=["Party City", "Oriental Trading", "Michaels"],
                items=[
                    "party supplies",
                    "balloons",
                    "decorations",
                    "cake for the party",
                    "party favors",
                    "banner",
                    "tableware",
                ],
                amount_range=(11.0, 68.0),
            ),
        ],
        standalone=[
            "drinks",
            "bar tab",
            "happy hour",
            "date night",
            "dinner date",
            "coffee with a friend",
            "game night snacks",
            "group gift",
            "office party contribution",
            "potluck contribution",
            "birthday dinner",
            "wedding contribution",
            "bachelor party",
            "bachelorette party",
            "split the bill",
            "friend's birthday",
            "night out with friends",
        ],
        amount_range=(12.0, 85.0),
        big_ticket=(130.0, 320.0),
    ),
    "Tourism": CategorySpec(
        groups=[
            Group(
                merchants=[
                    "Delta",
                    "United",
                    "American Airlines",
                    "Southwest",
                    "JetBlue",
                    "Alaska Airlines",
                    "Spirit",
                    "Frontier",
                    "Hawaiian Airlines",
                ],
                items=[
                    "flight",
                    "plane ticket",
                    "round trip flight",
                    "one way flight",
                    "flight home",
                    "baggage fee",
                    "checked bag",
                    "seat upgrade",
                    "flight change fee",
                    "early boarding",
                ],
                amount_range=(45.0, 620.0),
            ),
            Group(
                merchants=[
                    "Marriott",
                    "Hilton",
                    "Hyatt",
                    "Holiday Inn",
                    "Best Western",
                    "Motel 6",
                    "La Quinta",
                    "Four Seasons",
                    "Ritz-Carlton",
                    "Airbnb",
                    "Vrbo",
                    "Hostelworld",
                ],
                items=[
                    "hotel",
                    "hotel night",
                    "two nights at the hotel",
                    "resort fee",
                    "airbnb stay",
                    "vacation rental",
                    "hostel",
                    "room deposit",
                    "late checkout",
                    "extra night",
                ],
                amount_range=(65.0, 420.0),
            ),
            Group(
                merchants=["Hertz", "Enterprise", "Avis", "Budget Rent a Car", "Turo", "Sixt"],
                items=[
                    "rental car",
                    "car rental",
                    "rental car gas",
                    "car rental insurance",
                    "additional driver fee",
                    "one way drop off",
                ],
                amount_range=(38.0, 310.0),
            ),
            Group(
                merchants=[
                    "Expedia",
                    "Kayak",
                    "Booking.com",
                    "Priceline",
                    "Hotels.com",
                    "Viator",
                    "GetYourGuide",
                ],
                items=[
                    "trip booking",
                    "package deal",
                    "guided tour",
                    "boat tour",
                    "walking tour",
                    "excursion",
                    "day trip",
                    "tour booking",
                ],
                amount_range=(40.0, 380.0),
            ),
            Group(
                merchants=["TSA PreCheck", "Global Entry", "National Park Service", "CLEAR"],
                items=[
                    "tsa precheck",
                    "global entry",
                    "national park pass",
                    "park entrance fee",
                    "annual pass",
                    "application fee",
                ],
                amount_range=(20.0, 120.0),
            ),
        ],
        standalone=[
            "flight",
            "hotel",
            "airbnb",
            "travel insurance",
            "passport renewal",
            "visa fee",
            "souvenirs",
            "postcards",
            "airport parking",
            "shuttle to the hotel",
            "checked luggage",
            "ski pass",
            "lift ticket",
            "cruise deposit",
            "beach chairs",
            "snorkel rental",
            "vacation spending",
            "trip to see family",
            "airport food",
        ],
        amount_range=(28.0, 210.0),
        big_ticket=(320.0, 980.0),
        big_ticket_rate=0.3,
    ),
    "Subscription": CategorySpec(
        groups=[
            Group(
                merchants=[
                    "Netflix",
                    "Hulu",
                    "Disney+",
                    "Max",
                    "HBO Max",
                    "Prime Video",
                    "Apple TV+",
                    "Peacock",
                    "Paramount+",
                    "YouTube Premium",
                    "YouTube TV",
                    "Sling TV",
                    "Fubo",
                    "Criterion Channel",
                    "Shudder",
                    "Crunchyroll",
                    "Starz",
                    "Showtime",
                ],
                items=[
                    "subscription",
                    "monthly subscription",
                    "annual subscription",
                    "renewal",
                    "auto renewal",
                    "monthly plan",
                    "premium plan",
                    "family plan",
                    "monthly fee",
                    "ad free plan",
                ],
                amount_range=(6.99, 24.99),
            ),
            Group(
                merchants=["Spotify", "Apple Music", "Tidal", "Pandora", "SiriusXM", "Audible"],
                items=[
                    "subscription",
                    "monthly subscription",
                    "premium",
                    "family plan",
                    "student plan",
                    "annual plan",
                    "monthly fee",
                ],
                amount_range=(5.99, 19.99),
            ),
            Group(
                merchants=["iCloud", "Google One", "Dropbox", "OneDrive", "Backblaze", "Box"],
                items=[
                    "storage",
                    "cloud storage",
                    "extra storage",
                    "storage plan",
                    "monthly storage",
                    "annual plan",
                    "upgrade",
                ],
                amount_range=(2.99, 24.99),
            ),
            Group(
                merchants=[
                    "Adobe",
                    "Adobe Creative Cloud",
                    "Microsoft 365",
                    "Notion",
                    "Figma",
                    "ChatGPT Plus",
                    "Canva",
                    "Grammarly Premium",
                    "1Password",
                    "LastPass",
                    "NordVPN",
                    "ExpressVPN",
                    "GitHub",
                    "Squarespace",
                    "Namecheap",
                    "Zoom",
                ],
                items=[
                    "subscription",
                    "monthly plan",
                    "annual plan",
                    "license",
                    "seat",
                    "pro plan",
                    "renewal",
                    "monthly fee",
                ],
                amount_range=(4.99, 59.99),
            ),
            Group(
                merchants=[
                    "Planet Fitness",
                    "LA Fitness",
                    "24 Hour Fitness",
                    "Equinox",
                    "Orange Theory",
                    "ClassPass",
                    "Peloton",
                    "Crunch Fitness",
                    "YMCA",
                    "Gold's Gym",
                    "F45",
                ],
                items=[
                    "membership",
                    "monthly membership",
                    "annual membership",
                    "membership fee",
                    "monthly dues",
                    "class pack",
                    "initiation fee",
                ],
                amount_range=(10.0, 189.0),
            ),
            Group(
                merchants=[
                    "New York Times",
                    "Wall Street Journal",
                    "Washington Post",
                    "The Atlantic",
                    "The Economist",
                    "Substack",
                    "Medium",
                    "Patreon",
                ],
                items=[
                    "subscription",
                    "monthly subscription",
                    "digital subscription",
                    "annual subscription",
                    "membership",
                    "monthly pledge",
                ],
                amount_range=(4.0, 29.99),
            ),
            Group(
                merchants=[
                    "Verizon",
                    "T-Mobile",
                    "AT&T",
                    "Mint Mobile",
                    "Visible",
                    "Google Fi",
                    "Cricket",
                ],
                items=[
                    "phone bill",
                    "monthly plan",
                    "wireless bill",
                    "family plan",
                    "data plan",
                    "line charge",
                    "autopay",
                ],
                amount_range=(15.0, 165.0),
            ),
            Group(
                merchants=[
                    "Amazon Prime",
                    "Costco Membership",
                    "Sam's Club Membership",
                    "Walmart+",
                    "AAA",
                ],
                items=["membership", "annual membership", "membership renewal", "yearly fee"],
                amount_range=(60.0, 139.0),
            ),
            Group(
                merchants=[
                    "HelloFresh",
                    "Blue Apron",
                    "Factor",
                    "Dollar Shave Club",
                    "Chewy",
                    "BarkBox",
                ],
                items=["subscription box", "monthly box", "delivery", "subscription", "auto ship"],
                amount_range=(19.0, 89.0),
            ),
        ],
        standalone=[
            "gym membership",
            "monthly gym membership",
            "gym dues",
            "phone bill",
            "cell phone plan",
            "monthly phone plan",
            "wireless bill",
            "cloud storage",
            "icloud storage",
            "extra storage",
            "streaming service",
            "music streaming",
            "news subscription",
            "meal kit delivery",
            "subscription box",
            "domain renewal",
            "vpn subscription",
            "password manager",
            "software license",
            "monthly membership",
            "annual renewal",
            "auto renewed",
        ],
        amount_range=(5.99, 34.99),
        big_ticket=(69.0, 220.0),
    ),
}

CATEGORIES = list(SPEC.keys())
